metadata:
  name: proxy-{{name}}-secret
apiVersion: v1
data:
  STACKMGR_ACCESS_TOKEN: "{{access-token}}"
  STACKMGR_ARGOCD_ACCESS_TOKEN: "{{argo-access-token}}"
  STACKMGR_LONGHORN_ACCESS_TOKEN: "{{longhorn-access-token}}"
  STACKMGR_RKE2_ACCESS_TOKEN: "{{rke2-access-token}}"
kind: Secret

