apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy-{{name}} 
  name: proxy-{{name}}
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-{{name}}
  strategy: {}
  template:
    metadata:
      labels:
        app: proxy-{{name}}
    spec:
      containers:
      - name: proxy-{{name}}
        image: {{image}}:{{tag}}
        resources: {}
        envFrom:
        - configMapRef:
            name: proxy-{{name}}-config
            optional: false
        - secretRef:
            name: proxy-{{name}}-secret
            optional: false
      imagePullSecrets:
      - name: registry-credentials