metadata:
  name: stackmgr-proxy-secret
apiVersion: v1
data:
  #
  # clear-text access token to use in stackmgr cli (required)
  #
  STACKMGR_ACCESS_TOKEN: "thisismytoken123"
  #
  # base64-encoded access tokens for RKE2 and ArgoCD (required)
  #
  STACKMGR_ARGOCD_ACCESS_TOKEN: ""
  STACKMGR_RKE2_ACCESS_TOKEN: ""
kind: Secret

