# 2026 Copyright Talaryon Labs
# Project: StackManager.Proxy
# Maintainer: Talaryon Labs

FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app

EXPOSE 5380

COPY publish/ .
CMD dotnet StackManager.Proxy.dll